"""add stats cache

Revision ID: 950ec433084c
Revises: a85e58c7c473
Create Date: 2025-12-25 18:06:06.029988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950ec433084c'
down_revision = 'a85e58c7c473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', name='uq_stats_cache_user_year')
    )
    with op.batch_alter_table('stats_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stats_cache_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stats_cache_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_cache_year'))
        batch_op.drop_index(batch_op.f('ix_stats_cache_user_id'))

    op.drop_table('stats_cache')
    # ### end Alembic commands ###
