"""add titles table and title_id to watch_events

Revision ID: 99db421f6947
Revises: 950ec433084c
Create Date: 2025-12-30 13:04:55.333157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99db421f6947'
down_revision = '950ec433084c'
branch_labels = None
depends_on = None

FK_NAME = "fk_watch_events_title_id_titles"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'titles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('media_type', sa.String(length=20), nullable=False),
        sa.Column('genres_json', sa.Text(), nullable=False),
        sa.Column('cast_json', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', 'media_type', name='uq_titles_name_media_type')
    )

    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_titles_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_titles_name'), ['name'], unique=False)

    with op.batch_alter_table('watch_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_watch_events_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_watch_events_title_id'), ['title_id'], unique=False)
        batch_op.create_foreign_key(FK_NAME, 'titles', ['title_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_events', schema=None) as batch_op:
        batch_op.drop_constraint(FK_NAME, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_watch_events_title_id'))
        batch_op.drop_index(batch_op.f('ix_watch_events_media_type'))
        batch_op.drop_column('title_id')

    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titles_name'))
        batch_op.drop_index(batch_op.f('ix_titles_media_type'))

    op.drop_table('titles')
    # ### end Alembic commands ###
