"""add watch events

Revision ID: a85e58c7c473
Revises: 9ca4feab3c94
Create Date: 2025-12-24 23:00:30.016468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85e58c7c473'
down_revision = '9ca4feab3c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('watched_at', sa.Date(), nullable=False),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watch_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watch_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watch_events_watched_at'), ['watched_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watch_events_watched_at'))
        batch_op.drop_index(batch_op.f('ix_watch_events_user_id'))

    op.drop_table('watch_events')
    # ### end Alembic commands ###
